### ISSUE TITLE
Editor issue??

### ISSUE THREAD

**Issue by ctuxboy** [BoidCMS/BoidCMS#44]
I did a clean install without plugins and only the default theme but the issue doesn't solved.
So when create a post/page, everythings works good, but when update  a post or page and adding html-tags in the content field (textarea) then it converted/encode the text.
Example:
`<p>This is a test-page</p>` convert to  `&lt;p&gt;This is a test-page&lt;/p&gt;`

![Screenshot 2024-10-21 13 58 36](https://github.com/user-attachments/assets/d5a71c35-0333-4ee7-8070-761699c607fe)

And when looking to the page on the frontend, then the html-tags are showing

![Screenshot 2024-10-21 14 09 08](https://github.com/user-attachments/assets/2c196d3b-9ad7-4004-b7a9-4f0e1c84ba65)

See [this page](https://boid.gewoonsimpel.be/test-page)

Same with the demo content. After update the post/page ([hello-world](https://boid.gewoonsimpel.be/hello-world)), BoidCMS shows the html-tags on the frontend.

Test it with PHP 8.x

If you want  and try it, you can login on my test-website with the default username and password.

**Comment by shoaiyb** [comment]
It appears clearly that the problem isn't with **Trumbowyg integration plugjn** but rather the core. I also did a clean install and I can say I found where the problem is.

The cause of this whole problem is a single line: https://github.com/BoidCMS/BoidCMS/blob/bddffdcd74ab0745a457449ab606d97134978a86/app/app.php#L873

This can be seen as a consequence of passing the HTML content twice to the `htmlspecialchars` function trying to prevent XSS attacks as submitted by @diegojoel301 in https://github.com/BoidCMS/BoidCMS/issues/34.

The HTML gets escaped in the `App::create_page` method first. Hence, making the second attempt fatal.

**Comment by ctuxboy** [comment]
Hi @shoaiyb ,
Glad i can help and that you found the issue 😀
Regards,
Christophe

**Comment by shoaiyb** [comment]
Sorry to bring this back but I think this has to worked on and fixed before closing.

**Comment by shoaiyb** [comment]
The patch is in the `develop` branch and ready for testing now.

**Comment by ctuxboy** [comment]
> Sorry to bring this back but I think this has to worked on and fixed before closing.

Ah okay!

**Comment by ctuxboy** [comment]
Install the develop branch and works wel now :)
